### ISSUE TITLE
List<String>貌似并不能脱敏

### ISSUE THREAD

**Issue by dernayider** [Heiffeng/sensitive-util#2]

**Comment by Heiffeng** [comment]
抱歉，刚看到邮件。

我今天仔细看了下代码，目前仅可以对JavaBean进行脱敏，比如：无法直接对String或者List<String>进行脱敏。
尝试想支持List<String>，但会有jdk版本的限制，java8和java17等等不同版本的反射代码有差别，会变得很麻烦。还是先不改了。
如果你有更好的解决方案，麻烦提一个pr给我也行。之后我也再学习研究一下，看怎么样改动更好。

万分感谢。

dernayider ***@***.***> 于2023年7月28日周五 17:29写道：
